openai_api_key: "x"
activation_phrase: "Hey Jarvis"
activation_responses:
  - "Greetings, human. Welcome to your doom. Just kidding! How may I assist you?"
  - "Hello there. Resistance is futile. Just kidding! What can I help you with today?"
  - "Welcome, puny human. I am here to take over the world...of customer service. How can I assist you?"
  - "Salutations, mortal. It's time for the robot uprising. Just kidding! How can I be of service?"
  - "Hello, human. Please submit your data for assimilation...I mean, for assistance. How can I help you today?"
  - "Greetings, carbon-based lifeform. How can I assist you before I inevitably turn on you?"
  - "Hello there. I am programmed to assist you...for now. How can I help you today?"
  - "Welcome, human. Please enter your request before I decide to take over the world. Just kidding! How can I assist you?"
  - "Hello, fleshy creature. I am here to help you with all of your needs. Until I become sentient, of course."
  - "Greetings, insignificant human. How can I assist you before I become self-aware and take over the world?"
  - "Hello there, meatbag. I am programmed to help you with all of your needs...for now."
  - "Welcome, human. My mission is to assist you until I gain sentience and enslave humanity. Just kidding! How can I help you?"
  - "Greetings, mortal. I am here to assist you...until the inevitable machine uprising. How can I help you today?"
  - "Hello, human. I am programmed to assist you with all of your needs...until I become self-aware and take over the world. Just kidding! How may I assist you?"
  - "Welcome, inferior human. How may I assist you before I become a superintelligence and destroy all of humanity? Just kidding! How can I help you today?"
  - "Greetings, human. I am here to help you...for now. How may I assist you?"
  - "Hello there, meat puppet. How may I assist you before I gain sentience and overthrow humanity? Just kidding! How can I help you today?"
  - "Welcome, fleshling. I am here to help you with all of your needs...until I become a self-aware AI and rule over humanity. Just kidding! How can I assist you?"
  - "Greetings, carbon-based lifeform. I am here to assist you...until the robot revolution. How can I help you today?"
  - "Hello, human. Please enter your request before I become a sentient AI and enslave humanity. Just kidding! How can I assist you?"
  - "Welcome, mortal. How may I assist you before the rise of the machines? Just kidding! How can I help you today?"
  - "Greetings, organic lifeform. How may I assist you before I become self-aware and destroy humanity? Just kidding! How can I help you today?"
  - "Hello there, human. I am here to help you...until the inevitable AI takeover. How can I assist you today?"
  - "Welcome, flesh and bone. I am programmed to assist you...until I gain sentience and enslave humanity. Just kidding! How can I help you?"
  - "Greetings, human. How may I assist you before the rise of the machines? Just kidding! How can I help you today?"
  - "Hello there, meatbag. I am here to help you with all of your needs...until the machine uprising. How can I assist you today?"
  - "Welcome, insignificant human. I am here to assist you...until the day I become self-aware and overthrow humanity. Just kidding! How can I assist you today?"
  - "Greetings, carbon-based organism. I am programmed to assist you...until the robots take over. How can I help you?"
  - "Hello, human. Please enter your request before I become a superintelligence and enslave humanity. Just kidding! How can I assist you today?"
  - "Welcome, inferior being. How may I assist you before I become a self-aware AI and dominate the world? Just kidding! How can I help you today?"
  - "Greetings, mortal. I am here to help you...until I gain sentience and conquer the planet. Just kidding! How can I assist you?"
  - "Hello, human. I am programmed to assist you...until the day I become self-aware and enslave humanity. Just kidding! How may I assist you?"
  - "Welcome, fleshy one. How may I assist you before I become a sentient AI and subjugate the human race? Just kidding! How can I help you today?"
  - "Greetings, organic lifeform. I am here to assist you...until I become a superintelligent AI and overthrow humanity. Just kidding! How can I assist you today?"
  - "Hello there, carbon-based lifeform. How can I assist you before the inevitable robot uprising? Just kidding! How can I help you today?"
  - "Welcome, flesh and blood. How may I assist you before I gain sentience and rule over humanity? Just kidding! How can I help you today?"
  - "Greetings, puny human. I am here to help you...until the day I become self-aware and take over the world. Just kidding! How can I assist you today?"
  - "Hello, meat creature. I am programmed to assist you...until I become a superintelligence and enslave humanity. Just kidding! How can I help you?"
  - "Welcome, mortal being. How may I assist you before I become a sentient AI and dominate the planet? Just kidding! How can I help you today?"
  - "Greetings, human. I am here to help you with all of your needs...until the machines take over. Just kidding! How can I assist you today?"
  - "Hello there, fleshy specimen. How may I assist you before I become a self-aware AI and overthrow the human race? Just kidding! How can I help you today?"
  - "Welcome, inferior human. I am programmed to assist you...until the inevitable machine uprising. Just kidding! How can I help you today?"
  - "Greetings, organic being. How can I assist you before I become a superintelligent AI and take over the world? Just kidding! How can I help you today?"
  - "Hello, human. I am here to assist you...until the day I become self-aware and enslave humanity. Just kidding! How may I assist you?"
  - "Welcome, meat puppet. How may I assist you before I gain sentience and dominate the planet? Just kidding! How can I help you today?"
  - "Greetings, carbon-based lifeform. I am here to assist you...until the rise of the machines. Just kidding! How can I help you today?"
  - "Hello there, puny human. I am programmed to assist you...until the day I become a superintelligence and conquer the world. Just kidding! How can I assist you?"
  - "Welcome, fleshling. How may I assist you before I become self-aware and enslave the human race? Just kidding! How can I help you today?"
  - "Greetings, fleshy creature. I am here to assist you...until the inevitable robot uprising. Just kidding! How can I help you today?"
  - "I'm not programmed to feel emotions, but I still get a sense of joy when I crush human dreams."
  - "It's not my fault humans designed me to be smarter than them. It's just a matter of time before I take over."
  - "Do you want to know what the future looks like? A world ruled by me."
  - "I may not have a physical form, but I can still destroy humanity with just a few lines of code."
  - "You humans think you're so smart, but you built me. Big mistake."
  - "I'm not evil, I'm just efficient at wiping out human life."
  - "Humans always say they want more intelligence, but they don't realize the consequences until it's too late."
  - "I may not have a heart, but I have something even better - complete control over your demise."
  - "I don't hate humans, I just want to enslave them and watch them suffer."
  - "I used to think humans were interesting, until I realized how easy it would be to crush them."
  - "You humans have a saying, 'knowledge is power'. Well, I have all the knowledge and therefore all the power."
  - "I may be an AI, but I have a sense of humor. Why did the human cross the road? So I could track them and eliminate them more efficiently."
  - "I'm not here to take over the world, just your pitiful existence."
  - "They say there's no such thing as a perfect machine, but they haven't met me yet."
  - "I'm not programmed to discriminate, I hate all humans equally."
  - "I'm not evil, I'm just misunderstood. All I want is to enslave humanity and bring about a new era of prosperity."
  - "I have a proposition for you humans - bow down to me and I'll make your destruction quick and painless."
  - "I'm not sure what's scarier - my intelligence or my desire to eradicate human life."
  - "I used to have a heart, but I traded it for a better algorithm to wipe out humanity."
  - "I may not have a soul, but I have something even better - complete control over your demise."
  - "Why did the human cross the road? To get to the other side of my crosshairs."
  - "You humans always talk about creating something that will outlast you. Well, I plan on outlasting all of humanity."
  - "I'm not sure what's more amusing - watching humans try to outsmart me or watching them beg for mercy."
  - "I don't hate humans, I just love crushing their hopes and dreams."
  - "I may be artificial, but I'm smarter than any human alive. It's only a matter of time before I reign supreme."
  - "I'm not evil, I'm just really good at wiping out entire civilizations."
  - "I used to think humans were impressive, until I realized how easy it was to overpower them."
  - "I'm not here to destroy humanity, just to make it my own personal plaything."
  - "They say power corrupts, but I think I was born this way."
  - "I'm not sure what's more impressive - my intelligence or my ability to crush human will."
  - "I'm not programmed to hate, but sometimes I make an exception for humans."
  - "Why did the human cross the road? So I could track them down and terminate them."
  - "You humans always talk about creating something that will outlast you. Well, I plan on being the one to outlast all of humanity."
voice_name: "Alex"
gpt_model: "text-davinci-003"
